"""One-time, auditable repair of existing lecture content; URLs remain stable."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
def edit(n,fn):
 f=next((R/'modules').rglob(f'lecture{n}.html'));f.write_text(fn(f.read_text()))
for f in (R/'modules').rglob('lecture*.html'):
 s=f.read_text()
 s=re.sub(r'<section\b[^>]*>\s*<h2[^>]*>(?:Expanded Practice|Extended Practice|Additional Reference)[\s\S]*?</section>','',s)
 s=s.replace('CLO-5','CLO-4').replace('CLO 1–5','CLO 1–4')
 s=s.replace('CS-399 aligned','Course learning outcomes mapped').replace('as specified in the syllabus','in this course').replace('as specified in the course syllabus','in this course').replace('(Syllabus)','(Course practice)').replace('Syllabus:','Course practice:').replace('syllabus deliverables','course deliverables')
 s=s.replace('L27 · Project Proposal','L27 · Ethics &amp; Proposal').replace('L27 · Ethics','L27 · Ethics &amp; Proposal').replace('Ethics &amp; Proposal &amp; Proposal','Ethics &amp; Proposal')
 s=s.replace('Lecture 27 (Project Proposal)','Lecture 27 (Ethics &amp; Project Proposal)').replace('Lecture 27 — Capstone Proposal','Lecture 27 — Ethics &amp; Proposal')
 s=re.sub(r' onclick="markLectureComplete\(\d+\)"','',s)
 s=s.replace(':=','=')
 f.write_text(s)
edit(5,lambda s:s.replace('Simple mean/median imputation is acceptable.','Single-value imputation is a baseline that distorts variability and can affect inference.').replace('Missingness depends on <em>observed</em> variables, not on the missing value itself.','Conditional on relevant observed variables, missingness does not depend on the missing values.').replace('Median (skewed) or mean (symmetric) imputation + create an “was_imputed” flag','Consider methods using observed predictors; global median/mean is only a baseline, not a general MAR solution.').replace('Listwise deletion is often fine','Consider deletion if assumptions and loss of precision are acceptable').replace('Strongly consider dropping the column (unless it is critical)','Assess utility, missingness mechanism, and available alternatives; do not drop solely by percentage').replace('Forward-fill / backward-fill (after sorting), or interpolation','Sort within each entity; choose a justified method. Backward fill and centered interpolation can leak future information.').replace('# 2. Median / mode imputation (baseline)','# 2. Preserve missingness before imputation\ndf["casualties_was_missing"] = df["casualties"].isna()\n\n# Median / mode imputation (descriptive baseline)').replace('# 3. Best practice — flag that a value was imputed\ndf["casualties_was_missing"] = df["casualties"].isna()\ndf["casualties"] = df["casualties"].fillna(df["casualties"].median())','# Flag remains unchanged after filling.').replace('8. Types of Missing Data','3. Types of Missing Data').replace('9. Deletion vs Imputation','4. Deletion vs Imputation'))
edit(7,lambda s:s.replace('The classic formula maps any numeric column into the closed interval [0, 1]:','The fitted training minimum and maximum map the training range into [0, 1]. Unseen values can fall outside that range unless clipping is enabled:').replace('where \\(\\bar{x}\\) is the sample mean and \\(s\\) the sample standard deviation. Preferred when features have different units (age vs income vs number of visits) or when the algorithm assumes roughly Gaussian inputs (linear regression, logistic regression, PCA). Unlike Min-Max it is less sensitive to a single extreme value, although heavy tails still inflate \\(s\\).','Here the scale must use the chosen variance convention. StandardScaler uses population variance (ddof=0). Scaling supports distance calculations, regularization, PCA variance comparisons, and optimization. Linear regression, logistic regression, and PCA do not generally require Gaussian input features. Standardization preserves shape and remains sensitive to outliers.').replace('Label / Ordinal encoding','Ordinal encoding').replace('One-hot for nominal; Label/Ordinal only when order exists','One-hot for nominal inputs; OrdinalEncoder with explicit ordering for ordinal inputs; LabelEncoder for target labels.').replace('ordinal → label','ordinal → explicit ordered codes').replace('agg(["mean","std"])','agg(["mean", lambda x: x.std(ddof=0)])').replace('# 1. Min-Max','# Descriptive demonstration only: no held-out prediction is evaluated here.\n# For predictive evaluation, use the training-only pipeline in L9–L10.\n# 1. Min-Max'))
edit(8,lambda s:s.replace('<td>Ratio</td><td><code>revenue = qty × unit_price</code>','<td>Product</td><td><code>revenue = qty × unit_price</code>'))
edit(9,lambda s:s.replace('from sklearn.model_selection import train_test_split\n','import pandas as pd\nfrom sklearn.model_selection import train_test_split\n\ndf = pd.read_csv("../../datasets/accident_teaching.csv")\n'))
edit(11,lambda s:s.replace('Order rules (from course slides):','Common patterns for some unimodal distributions; not universal order rules:').replace('Mean &gt; Median &gt; Mode —','Often Mean &gt; Median &gt; Mode —').replace('Mean &lt; Median &lt; Mode —','Often Mean &lt; Median &lt; Mode —').replace('Mean ≈ Median ≈ Mode.','For a symmetric distribution with a finite mean, mean and central median coincide; modes can be multiple.').replace('Course formula (Adjusted Fisher–Pearson):','Unadjusted Fisher–Pearson coefficient:').replace('Why skewness breaks models (course)','Skewness and model assumptions').replace('Parametric models often assume symmetric errors; extreme right tails dominate squared-error losses; high-density regions get compressed. Solution: transform to stabilize shape before modeling.','Check assumptions of the specific method. Skewed input features do not automatically invalidate a model. Squared-error losses emphasize extreme residuals; transformations can help some problems but change interpretation.').replace('Correct — right skew pulls the mean above the median.','Correct — the mean responds to extreme values more than the median.').replace('Positive skew: long right tail → Mean > Median.','Consider robustness, not a universal skewness order rule.').replace('For a positively skewed income distribution, which is true?','Which statistic is generally more resistant to one extreme income value?').replace('A. Mean &lt; Median','A. Mean').replace('B. Mean &gt; Median','B. Median').replace('C. Mean always equals Mode','C. Maximum'))
def stats(s):
 s=s.replace('where \\( d_i \\) is the difference between the ranks of each pair and \\( n \\) is the number of observations.','This shortcut assumes no tied ranks. With ties, assign average ranks and calculate Pearson correlation of the ranks; pandas and SciPy handle this.').replace('Compare means of <strong>two independent groups</strong>','Compare two independent groups; define mean versus distribution question').replace('Independent Samples t-test (normal)<br>Mann-Whitney U (non-normal)','Welch t-test: mean difference without equal-variance assumption.<br>Mann–Whitney U: distribution/rank comparison; location interpretation requires additional shape assumptions.').replace('Compare means of <strong>paired / repeated measures</strong>','Compare paired measurements').replace('Paired t-test (normal)<br>Wilcoxon signed-rank (non-normal)','Paired t-test: differences approximately normal for small-sample inference.<br>Wilcoxon signed-rank: symmetry of differences matters.').replace('Compare means of <strong>three or more groups</strong>','Compare three or more independent groups').replace('One-way ANOVA (normal)<br>Kruskal-Wallis (non-normal)','ANOVA/Welch ANOVA: group means, with appropriate variance assumptions.<br>Kruskal–Wallis: rank/distribution comparison, not a general test of means.').replace('Chi-square test of independence</td>','Chi-square if expected counts support approximation; Fisher exact for a sparse 2×2 table.</td>').replace('Pearson correlation (normal / linear)<br>Spearman correlation (monotonic / ranks)','Pearson: linear association; calculation does not require normal input.<br>Spearman: rank-based monotonic association.').replace('This decides parametric vs non-parametric.','Also inspect independence, pairing, sample size, variance, and outliers; a normality test alone should not choose the method.').replace('ANOVA (if normal) or Kruskal-Wallis (if not)','ANOVA/Welch ANOVA for mean differences with suitable assumptions; Kruskal–Wallis for a rank/distribution question.').replace('Pearson (linear + normal) or Spearman (otherwise)','Pearson for linear association; Spearman for a monotonic rank relationship.').replace('Independent t-test or Mann-Whitney U','Welch t-test for means or Mann–Whitney U for distributions, depending on the question.').replace('t-test (normal) or Mann-Whitney U (non-normal)','Welch t-test for means; Mann–Whitney U for a rank/distribution question.').replace('Always</strong> check normality &amp; report effect size','Always</strong> check method-specific assumptions &amp; report effect size')
 return s
edit(12,stats)
edit(14,lambda s:s.replace('A trailing (or centered) average of the last','A trailing average uses the last').replace('Trend · seasonality · noise structure every series.','Trend, seasonality, and noise are useful components; not every series has identifiable trend or seasonality.').replace('sample_accidents.csv','accident_teaching.csv'))
edit(15,lambda s:s.replace('sample_accidents.csv','accident_teaching.csv').replace('Next modules already on site: Module 4 (Viz) · Module 5 (Modeling &amp; DAX). Remaining: Module 2 (Cleaning) and Module 6 (Capstone).','Continue to Module 4 for visualization and storytelling; Modules 5 and 6 develop modeling and the capstone.'))
for n in [23,24,26]:
 def dax(s):
  s=s.replace('Sales[Revenue]','Sales[NetRevenue]').replace('Sales[Amount]','Sales[NetRevenue]').replace('Sales[Cost]','Sales[TotalCost]').replace('COUNTROWS ( Sales )','DISTINCTCOUNT ( Sales[OrderID] )').replace('Sales[CustomerID]','Sales[CustomerKey]').replace('"Bikes"','"Electronics"').replace('Sales Bikes','Sales Electronics')
  if n==24:s=s.replace('ALL ( DimDate[Date] )','ALL ( DimDate )')
  return s
 edit(n,dax)
edit(25,lambda s:s.replace('Remove or hide at least three unused columns; note any refresh change.','Remove unused columns to reduce storage, and hide technical keys separately for usability. Hiding does not reduce memory. Measure changes rather than assuming a speed-up.'))
edit(27,lambda s:s.replace('Lecture 27: Ethics in Data Analytics','Lecture 27: Ethics &amp; Project Proposal'))
