"""Editable textbook diagrams and reproducible charts. No generated screenshots."""
from pathlib import Path
import html,json,textwrap
import numpy as np,pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats
R=Path(__file__).resolve().parents[1];O=R/'assets/visuals';O.mkdir(exist_ok=True)
plt.rcParams.update({'font.family':'DejaVu Sans','svg.fonttype':'none','font.size':10})
N='#183153';B='#2563eb';T='#0f766e';A='#b7791f';RED='#b44444'
manifest=[]
def record(name,title,cap,alt,lectures,question,answer):manifest.append(dict(file=name+'.svg',title=title,caption=cap,alt=alt,lectures=lectures,question=question,answer=answer))
def diagram(name,title,cards,cap,lectures,question,answer,edges=None):
 # vertical cards with optional backward review arrow; numerals reinforce sequence.
 w=900;h=130+len(cards)*125+110
 s=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" role="img" aria-labelledby="title desc"><title id="title">{html.escape(title)}</title><desc id="desc">{html.escape(cap)}</desc><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="{N}"/></marker></defs><rect width="100%" height="100%" fill="white"/><g font-family="sans-serif"><text x="40" y="50" font-size="27" font-weight="bold" fill="{N}">{html.escape(title)}</text>']
 for i,(head,body) in enumerate(cards):
  y=85+i*125;col=B if i==0 else (T if i==len(cards)-1 else N)
  s.append(f'<rect x="70" y="{y}" width="730" height="95" rx="10" fill="#f3f7fb" stroke="{col}" stroke-width="2"/><text x="90" y="{y+28}" font-size="20" font-weight="bold" fill="{col}">{i+1}. {html.escape(head)}</text>')
  for j,line in enumerate(textwrap.wrap(body,85)):s.append(f'<text x="90" y="{y+55+j*22}" font-size="17" fill="{N}">{html.escape(line)}</text>')
  if i<len(cards)-1:s.append(f'<path d="M435,{y+96} L435,{y+123}" stroke="{N}" stroke-width="2" marker-end="url(#arrow)"/>')
 for j,line in enumerate(textwrap.wrap(cap,90)):s.append(f'<text x="40" y="{h-75+j*22}" font-size="16" fill="{N}">{html.escape(line)}</text>')
 s.append('</g></svg>');(O/(name+'.svg')).write_text(''.join(s));record(name,title,cap,cap,lectures,question,answer)
def chart(name,title,cap,lectures,q,a,draw,size=(10,8)):
 fig=plt.figure(figsize=size);draw(fig);fig.suptitle(title,x=.08,ha='left',color=N,fontsize=17,weight='bold');fig.subplots_adjust(top=.88,bottom=.18,hspace=.5,wspace=.3)
 fig.text(.08,.035,'\n'.join(textwrap.wrap(cap,110)),fontsize=10,color=N)
 fig.savefig(O/(name+'.svg'),bbox_inches='tight',facecolor='white');plt.close(fig);record(name,title,cap,cap,lectures,q,a)
diagram('l1-analytics-types','One question, four analytical approaches',[
 ('Descriptive: what happened?','Orders fell from 1000 to 800: a 20% decrease.'),('Diagnostic: what is associated with the change?','Compare device, region, traffic, and checkout changes; investigate alternatives.'),('Predictive: what might happen?','Estimate future orders with a validated model and uncertainty.'),('Prescriptive: what should we do?','Choose an intervention subject to budget, risk, and an evaluation plan.')], 'Illustrative retail scenario. Observational diagnostics alone do not establish causation.',[1],'Can an association prove why orders fell?','No. A causal claim requires a suitable design and assumptions.')
# Custom branching architecture and ETL comparison.
def retail_pipeline():
 s=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1100"><title>Retail analytics pipeline</title><desc>Sources feed immutable raw storage, transformation and validation. Failed records go to review; curated facts and dimensions feed Power BI. Dashed connections denote operational support.</desc><defs><marker id="arr" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3z" fill="{N}"/></marker></defs><rect width="100%" height="100%" fill="white"/><g font-family="sans-serif"><text x="30" y="45" font-size="28" fill="{N}" font-weight="bold">Retail analytics pipeline</text>']
 def box(x,y,w,h,lines,col=N):
  s.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="8" fill="#f3f7fb" stroke="{col}" stroke-width="2"/>')
  for j,line in enumerate(lines):s.append(f'<text x="{x+w/2}" y="{y+28+j*23}" text-anchor="middle" font-size="17" fill="{col}">{html.escape(line)}</text>')
 def arrow(x1,y1,x2,y2,dash=False):s.append(f'<path d="M{x1},{y1} L{x2},{y2}" fill="none" stroke="{N}" stroke-width="2"'+(' stroke-dasharray="6 5"' if dash else '')+' marker-end="url(#arr)"/>')
 for x,lines in [(30,['Sales CSV']),(270,['Customer database']),(510,['Product API'])]:box(x,80,210,55,lines,B);arrow(x+105,135,375,175)
 for y,lines in [(175,['Ingestion']),(275,['Immutable raw storage']),(375,['Transform and validate']),(555,['Curated FactSales','Date / Product / Customer / Region']),(700,['Power BI semantic model']),(840,['Interactive report'])]:box(130,y,490,75,lines,T if y>=555 else N)
 for a,b in [(250,275),(350,375),(450,555),(630,700),(775,840)]:arrow(375,a,375,b)
 s.append(f'<text x="390" y="505" font-size="18" fill="{T}">Pass</text>');box(660,405,300,85,['Fail: quarantine','Review / correct records'],RED);arrow(620,415,660,430);s.append(f'<path d="M810,405 L810,355 L620,405" stroke="{RED}" fill="none" stroke-width="2" marker-end="url(#arr)"/>')
 box(680,650,270,125,['SUPPORT THROUGHOUT','Orchestration / monitoring','Access control / lineage'],N);arrow(680,680,620,590,True);arrow(680,710,620,750,True)
 s.append(f'<text x="30" y="975" font-size="17" fill="{N}">Solid arrows: data flow / reprocessing. Dashed: support connections.</text><text x="30" y="1010" font-size="17" fill="{N}">Raw records stay unchanged; verified corrections enter a new processing version.</text><text x="30" y="1045" font-size="17" fill="{N}">FactSales grain: one order line. Supporting layers apply to every stage.</text></g></svg>');(O/'l2-retail-pipeline.svg').write_text(''.join(s));record('l2-retail-pipeline','Retail analytics pipeline','Immutable raw records support traceability; validated facts and dimensions feed the semantic model. Failed records are reviewed.','Three sources feed ingestion, immutable storage, transformation, curated tables, Power BI and a report; a quarantine branch reprocesses corrections.',[2],'Why keep the raw layer?','To preserve provenance and enable reproducible reprocessing.')
retail_pipeline()
def etl_elt():
 s=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1050" role="img" aria-labelledby="title desc"><title id="title">ETL versus ELT</title><desc id="desc">Same source and target. ETL transforms in staging before loading; ELT loads raw data then transforms inside the warehouse.</desc><defs><marker id="arr" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3z" fill="{N}"/></marker></defs><rect width="100%" height="100%" fill="white"/><g font-family="sans-serif"><text x="35" y="45" font-size="28" font-weight="bold" fill="{N}">ETL versus ELT: where transformation happens</text>']
 def box(x,y,w,h,lines,col=N):
  s.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="9" fill="#f3f7fb" stroke="{col}" stroke-width="2"/>')
  for j,line in enumerate(lines):s.append(f'<text x="{x+w/2}" y="{y+30+j*24}" text-anchor="middle" font-size="18" fill="{col}">{html.escape(line)}</text>')
 def arrow(x1,y1,x2,y2):s.append(f'<path d="M{x1},{y1} L{x2},{y2}" stroke="{N}" fill="none" stroke-width="2" marker-end="url(#arr)"/>')
 box(250,80,500,70,['SAME SOURCE','Retail operational database'],B)
 for x,label in [(40,'ETL'),(535,'ELT')]:
  s.append(f'<text x="{x+200}" y="205" font-size="25" font-weight="bold" text-anchor="middle" fill="{N}">{label}</text>');box(x,230,400,70,['Extract'],B);arrow(500,150,x+200,230)
 box(40,365,400,95,['Transform + validate in staging','OUTSIDE the target'],A);arrow(240,300,240,365)
 s.append(f'<rect x="20" y="525" width="440" height="190" fill="#f0fdfa" stroke="{T}" stroke-dasharray="5 4"/><text x="45" y="555" font-size="17" fill="{N}">TARGET: analytics warehouse</text>');box(40,585,400,80,['Load curated data'],T);arrow(240,460,240,585)
 s.append(f'<rect x="515" y="330" width="440" height="385" fill="#f0fdfa" stroke="{T}" stroke-dasharray="5 4"/><text x="540" y="360" font-size="17" fill="{N}">TARGET: analytics warehouse</text>');box(535,390,400,80,['Load raw data'],B);arrow(735,300,735,390);box(535,550,400,95,['Transform + validate','INSIDE the target'],A);arrow(735,470,735,550)
 box(40,785,895,160,['Both require governance, validation, access control and lineage.','Both can retain raw history under a retention policy:','ETL can archive extracts; ELT can retain raw landing tables.','Choose by constraints, cost, privacy and workload.'],N)
 s.append(f'<text x="40" y="990" font-size="18" fill="{N}">Amber + location labels: transformation. Dashed boundary: target environment.</text><text x="40" y="1020" font-size="18" fill="{N}">Solid arrows: data flow. Neither approach is always superior.</text></g></svg>')
 (O/'l2-etl-elt.svg').write_text(''.join(s));record('l2-etl-elt','ETL versus ELT: transformation location','Same retail operational database and analytics warehouse in both. ETL transforms before loading; ELT loads raw then transforms inside the target. Both require governance and can retain raw history.','Two parallel data paths: ETL extraction, staging transformation outside the warehouse, and curated load; ELT extraction, raw warehouse load, and transformation within the warehouse. Amber and location labels identify transformation.',[2],'Can ETL retain raw history?','Yes. It can archive extracts before transformation; neither approach is universally superior.')
etl_elt()
diagram('l3-record-formats','One order in three representations',[('CSV row','OrderID,Region,Quantity → O1,North,3'),('JSON record','{"OrderID":"O1","customer":{"region":"North"},"Quantity":3}'),('Relational tables','Orders: O1, CustomerKey=7, Quantity=3; Customers: 7, North'),('Acquisition checks','Confirm schema, types, encoding, grain, permissions, and provenance.')], 'Representation affects parsing; CSV does not provide native types or a relational constraint system.',[3],'Does CSV enforce a unique key?','No. The reader must validate uniqueness.')
diagram('l4-decision-kpi','Business framing before analysis',[('Problem','Regional profitability appears to be falling.'),('Decision','Which region needs investigation before next quarter’s planning?'),('Question and scope','Compare 2024 Q1 net revenue, profit, and margin by region.'),('Define KPI','Margin = sum(Profit) / sum(NetRevenue); units = fraction or percent.'),('Evidence and action','Investigate differences; do not infer causes solely from a grouped summary.')], 'Define metric, denominator, time window, stakeholder, and decision before choosing a chart.',[4],'Why not average row margins?','That weights small and large sales equally; portfolio margin is a ratio of totals.')
# Existing requested assets are integrated as first-class entries.
existing={5:['l5-6-A_data_cleaning','l5-6-B_missingness_mechanisms'],6:['l5-6-C_mean_median_boxplot'],7:['l7-8-A_transformations','l7-8-B_unseen_minmax','l7-8-C_encoding'],8:['l7-8-D_feature_engineering'],9:['l9-10-A_split_comparison','l9-10-B_safe_workflow'],10:['l9-10-C_regression_capacity']}
metadata=json.loads((R/'scripts/visual_metadata.json').read_text())
for n,names in existing.items():
 for name in names:
  m=metadata[name];record(name,m['title'],m['caption'],m['alt'],[n],m['question'],m['answer'])
def shape(fig):
 rng=np.random.default_rng(11);samples=[rng.normal(0,1,3000),rng.lognormal(0,.65,3000),-rng.lognormal(0,.65,3000),np.r_[rng.normal(-2,.4,1500),rng.normal(2,.4,1500)]]
 for i,(x,title) in enumerate(zip(samples,['Symmetric unimodal','Right-skewed','Left-skewed','Symmetric bimodal'])):
  ax=fig.add_subplot(2,2,i+1);ax.hist(x,bins=45,color=B,alpha=.65,density=True);ax.axvline(x.mean(),color=RED,label=f'Mean {x.mean():.2f}');ax.axvline(np.median(x),color=T,ls='--',label=f'Median {np.median(x):.2f}');ax.set_title(title);ax.set_ylabel('Density');ax.legend(fontsize=8)
chart('l11-distribution-shapes','Shape is more than mean and SD','Synthetic samples, seed 11. Mean–median–mode ordering is not a universal theorem; a symmetric distribution can have two modes.',[11],'Does symmetry guarantee a unique mode?','No. The bimodal example has two peaks.',shape)
def dispersion(fig):
 ax=fig.add_subplot();x=np.array([-2,-1,0,1,2]);y=3*x
 for i,(z,label) in enumerate([(x,'Narrow'),(y,'Wide')]):ax.scatter(z,np.full(5,i),color=B if i==0 else T);ax.text(-6,.3+i,f'{label}: mean={z.mean():.0f}, SD={z.std(ddof=0):.3f}, IQR={np.percentile(z,75)-np.percentile(z,25):.0f}')
 ax.set_ylim(-.5,1.7);ax.set_yticks([0,1],['Narrow','Wide']);ax.set_xlabel('Unitless value')
chart('l11-spread','Same center, different spread','Exact samples: narrow [-2,-1,0,1,2]; wide [-6,-3,0,3,6]. Population SD; linear-interpolated quartiles.',[11],'Can equal means imply equal variability?','No.',dispersion,size=(10,5))
def correlations(fig):
 rng=np.random.default_rng(12);x=np.linspace(-2,2,100);ys=[x+rng.normal(0,.15,100),-x+rng.normal(0,.15,100),rng.normal(0,1,100),x*x,np.exp(x)]
 for i,(y,title) in enumerate(zip(ys,['Positive linear','Negative linear','No clear association','U-shaped','Monotonic nonlinear'])):
  ax=fig.add_subplot(3,2,i+1);ax.scatter(x,y,s=9,color=B);ax.set_title(f'{title}\nPearson={stats.pearsonr(x,y).statistic:.3f}; Spearman={stats.spearmanr(x,y).statistic:.3f}',fontsize=10);ax.set_xlabel('x');ax.set_ylabel('y')
chart('l12-correlations','Association depends on relationship shape','Synthetic examples, seed 12. A near-zero Pearson coefficient does not rule out a nonlinear association. Neither coefficient proves causation.',[12],'Why is the U-shape correlation weak?','Positive and negative slopes cancel in a linear summary.',correlations,size=(10,11))
diagram('l12-test-selection','Choose the question before the test',[('Independent numerical groups','Mean difference: Welch t-test for two; ANOVA/Welch ANOVA for three or more.'),('Paired numerical observations','Paired t-test on differences; Wilcoxon signed-rank needs suitable symmetry.'),('Rank / distribution comparison','Mann–Whitney U or Kruskal–Wallis; not general tests of means.'),('Categorical association','Chi-square: check expected counts; sparse 2×2 tables may use Fisher exact.'),('Numerical association','Pearson for linear; Spearman for monotonic ranks. Plot first.'),('Report and qualify','Independence, assumptions, effect size, confidence interval, p-value, multiplicity.')], 'A normality test alone does not choose the method. The design and estimand determine interpretation.',[12],'What does Mann–Whitney generally compare?','Distributions/ranks; a location interpretation needs additional assumptions.')
small=pd.DataFrame({'Region':['North','North','South','South','North','South'],'Category':['A','B','A','B','A','B'],'Revenue':[100,50,80,20,30,40]})
def pivot(fig):
 for i,(frame,title) in enumerate([(small,'Raw rows'),(small.groupby('Region').Revenue.sum().reset_index(),'Group totals'),(small.pivot_table(index='Region',columns='Category',values='Revenue',aggfunc='sum',fill_value=0,margins=True).reset_index(),'Pivot layout')]):
  ax=fig.add_subplot(3,1,i+1);ax.axis('off');ax.set_title(title,loc='left');tb=ax.table(cellText=frame.values,colLabels=frame.columns,loc='center');tb.auto_set_font_size(False);tb.set_fontsize(11);tb.scale(1,1.5)
chart('l13-group-pivot','Split, aggregate, and change layout','Synthetic six-row example. North=180, South=140; grand total=320. Pivot totals reconcile to raw revenue.',[13],'What is the pivot grand total?','320.',pivot,size=(9,10))
def time(fig):
 rng=np.random.default_rng(14);t=np.arange(36);trend=100+.8*t;season=12*np.sin(2*np.pi*t/12);noise=rng.normal(0,3,36);y=trend+season+noise;ma=pd.Series(y).rolling(3,min_periods=3).mean()
 for i,(values,label) in enumerate([(y,'Observed and trailing 3-month mean'),(trend,'Known synthetic trend'),(season,'Known annual seasonal component'),(noise,'Generated noise')]):
  ax=fig.add_subplot(4,1,i+1);ax.plot(t+1,values,color=B);ax.set_title(label,loc='left',fontsize=10);ax.set_ylabel('Synthetic index units');ax.grid(alpha=.2)
  if i==0:ax.plot(t+1,ma,color=T,label='Trailing 3 months');ax.legend(fontsize=9)
 ax.set_xlabel('Month number')
chart('l14-components','Time-series components and smoothing','Synthetic 36 months, seed 14. Known construction: trend + annual seasonality + noise. This does not prove such components exist in arbitrary real data.',[14],'Why are the first two full-window averages absent?','Three observations are required for a complete trailing window.',time,size=(10,10))
acc=pd.read_csv(R/'datasets/accident_teaching.csv',parse_dates=['date'])
def eda(fig):
 ax=fig.add_subplot(211);counts=acc.groupby('region').casualties.sum();ax.bar(counts.index,counts.values,color=B);ax.set_ylabel('Casualties (count)');ax.set_title('Count by region; exposure unknown')
 ax=fig.add_subplot(212);s=acc.set_index('date').resample('MS').casualties.sum();ax.plot(s.index,s.values,color=T);ax.set_ylabel('Casualties (count)');ax.set_title('Monthly recorded casualties')
chart('l15-eda','EDA answers questions with limitations','Generated synthetic accidents, seed 399. Counts lack traffic exposure and reporting denominators, so they do not establish real-world road risk.',[15],'Does the highest casualty count identify the most dangerous region?','No. Exposure and reporting coverage must be considered.',eda)
def selection(fig):
 vals=[40,20,30,10];labs=['North','South','East','West']
 for i,title in enumerate(['Bar: category comparison','Pie: composition','Line: inappropriate categorical connection']):
  ax=fig.add_subplot(3,1,i+1);ax.set_title(title,loc='left')
  if i==0:ax.bar(labs,vals,color=B);ax.set_ylabel('Revenue (USD)');ax.set_ylim(0,45)
  elif i==1:ax.pie(vals,labels=labs,autopct='%1.0f%%',colors=['#2563eb','#0f766e','#b7791f','#94a3b8'])
  else:ax.plot(labs,vals,'o-',color=RED);ax.set_ylabel('Revenue (USD)')
chart('l16-chart-choice','Same data, different visual questions','Synthetic values: North=40, South=20, East=30, West=10 USD. Regions have no natural continuous order; a connecting line can imply one.',[16],'Which chart best compares regional revenue?','A bar chart with an appropriate order.',selection,size=(9,12))
def redesign(fig):
 labs=['North','South','East','West'];v=[40,20,30,10]
 ax=fig.add_subplot(211);ax.bar(labs,v,color=['red','blue','green','purple']);ax.set_ylim(8,42);ax.grid(True);ax.set_title('Before: Chart 1; truncated baseline; decorative colors')
 ax=fig.add_subplot(212);idx=np.argsort(v);ax.barh(np.array(labs)[idx],np.array(v)[idx],color=['#94a3b8']*3+[T]);ax.set_xlim(0,45);ax.set_xlabel('Revenue (USD)');ax.set_title('After: North has the highest revenue in this synthetic sample');ax.spines[['top','right']].set_visible(False)
chart('l17-redesign','Make the comparison easier to read','Same synthetic values in both panels. The improved chart uses a zero baseline, ranking, units, and a focused title.',[17],'Why is the zero baseline important for bars?','Bar length encodes magnitude; truncation distorts that comparison.',redesign)
def waterfall(fig):
 vals=[100,20,15,-10,125];labels=['Start','Price','Volume','Cost','End'];base=[0,100,120,135,0]
 ax=fig.add_subplot(211)
 for i,(v,b) in enumerate(zip(vals,base)):ax.bar(i,abs(v),bottom=b if v>=0 else b+v,color=N if i in [0,4] else (T if v>0 else RED))
 ax.set_xticks(range(5),labels);ax.set_ylabel('Profit (USD)');ax.set_title('Waterfall: 100 + 20 + 15 − 10 = 125')
 ax=fig.add_subplot(212);v=[1000,300,120,60];lab=['Visitors','Product views','Carts','Purchases'];ax.barh(lab[::-1],v[::-1],color=B);ax.set_xlabel('People (count)');ax.set_title('Funnel: stage conversions 30%, 40%, 50%; overall 6%')
chart('l18-waterfall-funnel','Advanced forms for specific questions','Synthetic examples. A waterfall reconciles signed contributions. Funnel stages describe the same defined cohort; stage conversion and overall conversion differ.',[18],'What is overall purchase conversion?','60/1000 = 6%.',waterfall)
def multiples(fig):
 t=np.arange(6);values=[[10,12,14,16,15,19],[18,17,16,18,20,21],[5,7,8,10,9,12]]
 for i,(v,label) in enumerate(zip(values,['North','South','East'])):
  ax=fig.add_subplot(3,1,i+1);ax.plot(t+1,v,'o-',color=B);ax.set_ylim(0,25);ax.set_ylabel(label+'\nUSD');ax.grid(alpha=.2)
 ax.set_xlabel('Month number')
chart('l18-small-multiples','Shared scales support comparison','Synthetic six-month regional revenue. All panels use 0–25 USD, so vertical positions are comparable.',[18],'How would independent y-scales change the impression?','They can hide differences in level even while showing each trend clearly.',multiples)
def wire(fig):
 ax=fig.add_subplot();ax.axis('off')
 boxes=[(.02,.8,.96,.1,'Decision: which region needs investigation?'),(.02,.63,.3,.12,'Revenue KPI\nDefinition + period'),(.35,.63,.3,.12,'Profit margin\nRatio of totals'),(.68,.63,.3,.12,'Distinct orders\nOrderID grain'),(.02,.18,.6,.38,'Monthly trend\nContext for change'),(.66,.18,.32,.38,'Region comparison\nIdentify exceptions'),(.02,.03,.96,.1,'Filters: Year / Region · Source, units, definitions, limitations')]
 for x,y,w,h,l in boxes:ax.add_patch(plt.Rectangle((x,y),w,h,fill=False,edgecolor=N,lw=1.5));ax.text(x+w/2,y+h/2,l,ha='center',va='center',color=N)
chart('l19-wireframe','A dashboard organized around a decision','Conceptual wireframe, not a software screenshot. KPI definitions and filter context make numbers interpretable.',[19,26],'Why show filter context?','The same measure changes under different dates and segments.',wire,size=(10,7))
diagram('l20-query-shaping','Power Query: shape before loading',[('Import and profile','Choose sales_multiyear.csv; set Date, key, numeric and currency types explicitly.'),('Merge: enrich rows by a key','Sales.ProductKey joins unique DimProduct.ProductKey; validate row counts.'),('Append: stack matching schemas','2022 rows + 2023 rows; preserve columns and check combined row count.'),('Unpivot: columns become observations','Region, Jan, Feb → Region, Month, Amount; write the new grain.'),('Load and verify','Compare totals. CSV sources do not support database query folding.')], 'Conceptual workflow, not a fabricated Power BI screenshot. The lab supplies exact Desktop steps.',[20],'How does append differ from merge?','Append adds rows; merge joins columns by keys.')
diagram('l21-report-interactions','Report interactions have distinct purposes',[('Year / region slicers','Set filter context for cards, trend, and region comparison.'),('Cross-filter / cross-highlight','Choose whether clicking a visual filters or highlights another.'),('Drillthrough','Open a detail page with the selected entity filter.'),('Publish and refresh','Use an authorized workspace, appropriate sharing permissions, and scheduled refresh.'),('Access control','Use roles and row-level security where needed; verify as each viewer.')], 'A report and a Power BI Service dashboard are different objects. The bundled HTML report is a teaching implementation, not Power BI UI.',[21],'Does a screenshot demonstrate filter behavior?','No; test the interactive report.')
# Star schema in SVG with exact keys.
s=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 950 850"><title>Order-line star schema</title><desc>Unique dimension keys filter Sales through one-to-many relationships; Sales grain is one order line.</desc><rect width="100%" height="100%" fill="white"/><g font-family="sans-serif"><text x="30" y="45" font-size="28" fill="{N}">Star schema: one row per order line</text><defs><marker id="arr" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3z" fill="{N}"/></marker></defs>'
for x,y,w,h,title,body in [(330,300,290,220,'Sales','OrderID + LineID (grain)|OrderDate / ProductKey|CustomerKey / RegionKey|Quantity / NetRevenue / Profit'),(330,90,290,120,'DimDate','Date (unique)|Year / Month / Quarter'),(20,330,260,120,'DimProduct','ProductKey (unique)|Product / Category'),(670,330,260,120,'DimRegion','RegionKey (unique)|Region'),(330,610,290,120,'DimCustomer','CustomerKey (unique)|Segment')]:
 s+=f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="#eef2f7" stroke="{N}"/><text x="{x+15}" y="{y+30}" font-size="22" fill="{N}">{title}</text>'
 for i,t in enumerate(body.split('|')):s+=f'<text x="{x+15}" y="{y+62+i*30}" font-size="16" fill="{N}">{html.escape(t)}</text>'
for a,b,lab in [((475,210),(475,300),'1 → *'),((280,390),(330,390),'1 → *'),((670,390),(620,390),'1 → *'),((475,610),(475,520),'1 → *')]:s+=f'<path d="M{a[0]},{a[1]} L{b[0]},{b[1]}" stroke="{N}" stroke-width="2" marker-end="url(#arr)"/><text x="{(a[0]+b[0])/2+8}" y="{(a[1]+b[1])/2-12}" font-size="17" fill="{N}">{lab}</text>'
s+=f'<text x="30" y="795" font-size="17" fill="{N}">Single-direction filtering: dimension → fact. OrderID can repeat across lines.</text></g></svg>';(O/'l22-star.svg').write_text(s);record('l22-star','Order-line star schema','Dimension keys are unique. Sales contains one order line; distinct orders differ from row count.','Four dimensions connect with one-to-many dimension-to-fact arrows to Sales.',[22],'Can OrderID be the unique key of this fact?','No; orders can have multiple lines. Use OrderID plus LineID.')
diagram('l23-context','Row context and filter context',[('Four lines, three orders','North: O1/L1=100, O1/L2=50. South: O2/L1=200, O3/L1=150 USD.'),('Row-level calculation','Quantity × UnitPrice × (1 − Discount) evaluates a value for each line.'),('No region filter','Total=500; Line Count=4; Order Count=3; AOV=500/3 USD.'),('North filter context','Total=150; Line Count=2; Order Count=1; AOV=150 USD.'),('Context transition','CALCULATE can convert row context into filter context; use keys to identify rows.')], 'Synthetic example. COUNTROWS measures lines; DISTINCTCOUNT(OrderID) measures orders.',[23],'What is AOV if you divide total by four lines?','125 USD is average line revenue, not average order value.')
diagram('l24-time-context','Date sets control time intelligence',[('Current selection','February 2024: February 1–29, within the complete 2022–2024 calendar.'),('Year to date','January 1–February 29, 2024; other dimension filters remain.'),('Prior-year period','February 2023 for a February-2024 comparison; document leap-day semantics.'),('Full-history cumulative','All calendar dates up to the selected cutoff; remove the whole DimDate context.'),('Selected-window cumulative','Only selected dates up to the cutoff; use ALLSELECTED and explain the window.')], 'Classic date-column patterns require a suitable calendar and relationship. A missing prior-year fact period may correctly return BLANK.',[24],'Why remove the whole date table for full-history totals?','A remaining Year/Month filter could constrain the cumulative date set.')
diagram('l25-performance','Measure performance; do not invent improvements',[('Baseline','Record Performance Analyzer duration for the same visual and filter state.'),('Reduce unnecessary storage','Remove unused columns; retain relationship keys. Hiding only affects usability.'),('Simplify model and measures','Check cardinality, single-direction relationships, unnecessary iterators, and Auto Date/Time.'),('Repeat controlled measurement','Use the same machine, query, refresh state, and repeated runs; separate cold/warm effects.'),('Report evidence','Compare durations and model size; a change may not improve speed.')], 'Procedure, not fabricated benchmark results. Native Power BI measurements must be supplied by executing Desktop.',[25],'Does hiding a column reduce model storage?','No; removing a stored column can.')
diagram('l26-project','Dashboard project acceptance criteria',[('Frame','Specify one decision, KPI formulas, grain, units and time scope.'),('Build','Load star tables, define measures, and test known reference totals.'),('Interact','Test year and region filters, reset, detail views, and no-data states.'),('Optimize','Measure performance; simplify only with verified correctness.'),('Submit','Model/report, data dictionary, QA notes, limitations, and screenshots.')], 'The bundled interactive HTML report demonstrates concepts; a Power BI submission still requires a .pbix built in Desktop.',[26],'What proves the dashboard total is correct?','Reconcile it to source/Python reference totals under identical filters.')
diagram('l27-ethics','Ethics at every project stage',[('Collection','Minimize fields, verify permission and coverage; avoid unnecessary identifiers.'),('Cleaning','Inspect group-dependent missingness; do not erase rare valid records.'),('Analysis','Report uncertainty and alternatives; avoid cherry-picking and causal overclaims.'),('Visualization and sharing','Use honest scales, accessible design, permissions and aggregation.'),('Pseudonymization is not anonymity','Hashed IDs may remain linkable; assess re-identification and retention.')], 'Risk review is continuous. Synthetic teaching data avoids exposing patient or customer identities.',[27],'Does hashing guarantee anonymous data?','No; linkage and re-identification can remain possible.')
diagram('l27-proposal','Capstone proposal canvas',[('Decision and scope','Stakeholder, problem, analytical questions, KPIs, units and denominator.'),('Data','Source, permission, grain, provenance, coverage, and quality risks.'),('Methods','Cleaning, EDA, model/report approach, validation, and alternatives.'),('Deliverables and milestones','Proposal → clean data/EDA → dashboard QA → presentation.'),('Acceptance and limitations','Reference checks, uncertainty, privacy, feasibility, and explicit exclusions.')], 'Proposal criteria are course guidance, not a claim of institutional assessment policy.',[27],'What makes a proposal feasible?','A bounded question, accessible data, realistic methods and explicit acceptance criteria.')
diagram('l28-checkpoints','Capstone lab checkpoints',[('Source and profile','Record grain, units, schema, permissions, and missingness.'),('Clean and validate','Keep raw data; log decisions and quarantine; check totals.'),('EDA','Inspect distributions, groups, and time; distinguish counts from rates.'),('Draft evidence','Link each insight to a chart and limitation.'),('Feedback loop','Failed checks return to their source stage; revise data/methods before dashboard build.')], 'A surprising finding is not mandatory: honest, reproducible evidence is more valuable than a dramatic narrative.',[28],'What if the EDA contradicts the proposal hypothesis?','Report it honestly and revise the interpretation.')
diagram('l29-qa','Final dashboard quality checks',[('Numbers','Match source/Python totals and distinct counts at the same grain.'),('Filters and dates','Test combinations, subtotals, date gaps, and legitimate no-data states.'),('Access and ethics','Test roles, remove unnecessary identifiers, expose limitations.'),('Performance and accessibility','Measure actual loads; test keyboard, contrast and labels.'),('Fix and retest','Trace a failure to data, measures or interactions; preserve a correction log.')], 'Example failures: multiplied join rows, order-line counts mislabeled as orders, stale refresh, or inaccessible color-only status.',[29],'How can a plausible number still be wrong?','Incorrect grain, joins or filter context can produce believable but invalid totals.')
diagram('l30-story','Presentation: evidence to decision',[('Question','Who needs to decide what, and why does the KPI matter?'),('Data and methods','Source, grain, cleaning, validation, and important assumptions.'),('Evidence','Show 2–3 clear findings, the filter context, and reproducible numbers.'),('Recommendation','State a proportionate next action and how it would be evaluated.'),('Limits and defence','Uncertainty, bias, unavailable denominators, and what cannot be claimed.')], 'Use associated with for observational findings. Reserve causal claims for appropriate designs and assumptions.',[30],'What belongs next to the recommendation?','Its evidence, limits, and an evaluation plan.')
(O/'manifest.json').write_text(json.dumps(manifest,indent=2));print('Visual assets in manifest:',len(manifest))

# Portable SVG line endings and whitespace.
for asset in O.glob("*.svg"):
 asset.write_text("\n".join(line.rstrip() for line in asset.read_text().splitlines())+"\n")
