"""Integrate lesson-specific practice, accessible visuals and a complete static search index."""
from pathlib import Path
import re, json, html
import xml.etree.ElementTree as ET
R=Path(__file__).resolve().parents[1]
visuals=json.loads((R/'assets/visuals/manifest.json').read_text())
labs={2:['L2_Python_Basics_Comprehensive_Lab'],3:['L3_Python_Data_Structures_Guide','L3_Data_Acquisition_and_Scraping'],4:['L4_Analytical_Thinking_Practical_Lab'],5:['L5_Data_Quality_and_Profiling'],6:['L6_Outliers_and_Noise_Lab'],7:['L7_Data_Transformation_Lab'],8:['L8_Feature_Engineering_Lab'],9:['L9_Splitting_and_Validation_Lab'],10:['L10_Predictive_Pipeline_Lab'],11:['L11_Descriptive_Statistics_Lab'],12:['L12_Correlation_Lab'],13:['L13_SQL_and_Aggregation_Lab'],14:['L14_Time_Series_Lab'],15:['L15_EDA_Case_Study'],20:['L20_PowerBI_Power_Query_Lab'],22:['L22_PowerBI_Data_Modeling_Lab'],23:['L23_L24_PowerBI_DAX_Time_Intelligence_Lab'],24:['L23_L24_PowerBI_DAX_Time_Intelligence_Lab']}
# A concrete task, a checkable acceptance condition, and an interpretation per lecture.
practice={
1:('Frame a decision','Write a stakeholder, decision, measurable outcome and analysis scope for declining orders.','A 20% order decline describes a change; it does not identify its cause. Separate evidence from a hypothesis.'),
2:('Defend the architecture','Trace an invalid quantity from extraction to quarantine and correction. Identify where permissions, schema checks and lineage apply.','Immutable raw storage retains the original record; correction creates a new processing version. ETL and ELT both require governance.'),
3:('Acquire and join safely','Use the local CSV/JSON/HTML examples and join ProductKey with validate="many_to_one". Record source, retrieval date, permission, grain and types.','A join must preserve the order-line count. A duplicated dimension key can inflate totals even when the code runs.'),
4:('Define a useful metric','Calculate regional margin for 2024 Q1 as sum(Profit)/sum(NetRevenue). Specify the audience and the action a low margin would trigger.','A ratio of totals weights transactions by revenue. An average of row margins answers a different question.'),
5:('Keep a cleaning decision log','Profile dirty_sales.csv; remove exact duplicates, standardize region strings, coerce dates, quarantine impossible quantities/dates, and flag missing quantity before imputation.','Keep raw inputs. The median baseline does not restore missing-data uncertainty. Compare results including and excluding imputed rows; predictive imputation must be fitted on training data.'),
6:('Flag rather than automatically delete','Compare the six-value example with the original five values and state the percentile convention. Identify the fences and observed whisker endpoints.','For [10,12,13,14,15,100], linear Q1=12.25 and Q3=14.75; fences 8.5 and 18.5; whiskers 10 and 15. Statistical unusualness does not prove a data error.'),
7:('Separate fitting from transforming','Reproduce all transformations of [10,20,30,40,100]. Fit the min–max scaler only once, then transform 120 without clipping.','Population mean=40 and SD=10√10. The unseen scaled value is 11/9. Standardization changes location and scale, preserving shape rather than making a distribution normal.'),
8:('Define features and their availability','Calculate the worked transaction and derive month/weekday from the assumed date 2024-01-08. Define the prediction timestamp before building historical features.','Gross=600 USD; net=540; cost=360; profit=180; margin=1/3. Month=1; weekday=0 (Monday). Realized profit or later returns can leak future information.'),
9:('Match validation to the data structure','Use stratification for independent class records, group splitting for repeated patients, and forward validation for dates. Verify groups do not overlap.','A random split is unsuitable for evaluating future forecasting or new-patient generalization when related records cross partitions. Stratification alone does not solve these issues.'),
10:('Evaluate a full predictive recipe','Run the pipeline lab: imputation, polynomial features, scaling and regularized regression. Select settings using training-side folds and compare a baseline on the final held-out test.','Every learned preprocessing step must be fitted inside each training fold. The degree-1/2/15 chart is a prespecified capacity demonstration, not permission to tune on test errors.'),
11:('Report definitions and uncertainty','Compute sample versus population standard deviation, adjusted versus unadjusted skewness, excess kurtosis and a mean confidence interval on the notebook’s stated examples.','Common mean/median/mode orderings are heuristics, not theorems for every distribution. Zero skewness need not imply symmetry; kurtosis is about tail behavior, not simply peak height.'),
12:('Choose the estimand before the test','Run Welch independent means, paired differences, Mann–Whitney, chi-square and Fisher examples. Report effect direction, magnitude, confidence interval where appropriate, sample size and p-value.','A p-value is not the probability the null is true. Rank tests compare distributions unless additional shift assumptions support a median interpretation; sparse counts may require exact methods.'),
13:('Learn SQL and aggregation together','Run SQLite SELECT, WHERE, JOIN, GROUP BY, HAVING, CASE, a CTE and a window function in the lab. Reconcile grouped totals against Pandas and a pivot table.','NULL comparisons use IS NULL, not = NULL. Joins can duplicate rows; check key cardinality and aggregation grain before interpreting totals.'),
14:('Respect temporal order','Use the 397-observation monthly electric-production series. Sort dates, verify monthly coverage, compute trailing 12-month means and 12-month change, and inspect the trend/seasonality example.','Trailing windows use past/current observations; centered windows and backward filling can expose future values. This lesson is descriptive; a forecast needs chronological validation and a naive baseline.'),
15:('Complete an EDA narrative','Use accident_teaching.csv to inspect schema, missingness, duplicates, region/month counts and severity distribution. Deliver three observations with units and limitations.','The 1800 records are generated for teaching. More incidents do not establish greater risk without exposure denominators such as traffic volume or distance traveled; association is not causation.'),
16:('Choose an encoding for the question','Use a bar for regional comparison and a line for ordered time. Compare the same four values with a pie and state what is lost.','Bars normally need a zero baseline. Unordered regions should not be connected as a time trend. Avoid 3D distortions and label units, source and period.'),
17:('Redesign for interpretation','Redraw the before/after chart with a zero baseline, sensible ordering and one message. Test grayscale legibility and keyboard access to any controls.','Use color plus labels or shapes. If using a truncated axis for a line chart, label it clearly and explain the focus; bar length must represent magnitude.'),
18:('Check advanced chart semantics','Reconcile the signed waterfall and calculate each funnel conversion. Compare regional trends using shared scales in small multiples.','Waterfall: 100+20+15−10=125. Funnel: 30%, 40%, 50% stage rates and 6% overall for the same cohort. Choropleths usually need appropriate rates and geographic coverage, not raw population-driven counts.'),
19:('Build a decision-oriented layout','Explore the bundled retail report. Change Year and Region and verify cards, chart and table share the same context. Sketch a layout for a specific audience.','Every KPI needs a definition, date window, units and denominator. The browser report is a working teaching example, not a Power BI screenshot.'),
20:('Shape data before loading','Follow the Desktop lab: set data types; profile the complete dataset; merge a unique product dimension; append compatible yearly rows; unpivot a monthly table; document each step.','CSV sources do not offer database query folding. Verify folding only for supported connectors and transformations. Preserve null indicators before replacement.'),
21:('Test interactions and delivery','Test slicers, edit interactions, drillthrough and reset behavior. In your authorized Power BI workspace test refresh and View as role before sharing.','A report is not a Service dashboard. Hiding columns or visuals is not security. Row-level security and workspace roles must be validated with realistic viewer permissions.'),
22:('Validate the star schema','Import Sales and DimDate/DimProduct/DimCustomer/DimRegion. Use unique dimension keys with 1:* single-direction relationships; Date connects to OrderDate. Reconcile reference totals.','One row is one order line. OrderID repeats, so order count is DISTINCTCOUNT(OrderID), not COUNTROWS. Use a continuous date table and mark it as the date table.'),
23:('Observe filter context','Create the measures in resources/powerbi-measures.dax separately. Compare totals, category filters, KEEPFILTERS, REMOVEFILTERS and ALLSELECTED under region/category slicers.','The four-line visual has sales 500 USD and 3 orders; North has 150 USD and 1 order. Measures respond to filter context; a calculated column is evaluated per row during model processing.'),
24:('Test time intelligence across years','Use the complete 2022–2024 dataset and marked date table. Compare YTD and previous-year totals, then contrast full-history and selected-period running totals with slicers.','Clear ALL(DimDate), not just its Date column, when a cumulative measure should ignore Year/Month filters. Prior-year comparisons require comparable periods and explicit leap-day/calendar semantics.'),
25:('Measure a performance change','Use Performance Analyzer to record a baseline interaction, query duration and environment. Change one factor, repeat the same interaction and record the result.','No measured performance values are invented here. Removing unused columns differs from hiding them; constrain cardinality and relationships before adding complex DAX.'),
26:('Deliver a reconciled report','Build the retail semantic model, apply all base measures and accessible interactions, and compare cards and annual totals to reference_totals.json. Document refresh and access.','A passing screenshot is insufficient: test multiple filters, distinct order counts, margins, dates and security. The browser report supports exploration; Desktop is required to validate actual DAX.'),
27:('Submit an ethical proposal','Use the course-guide rubric to specify the problem, question, metric, data inventory, permission, privacy, method, validation and deliverables.','Remove identifiers where possible, minimize collection, protect access and examine subgroup validity. State uncertainty and avoid implying observational association is causal.'),
28:('Execute with checkpoints','Keep a run log with source version, cleaning decisions, environment, key tests and unresolved questions. Review milestones against the proposal.','A reproducible checkpoint includes code and inputs, not only outputs. Preserve evidence when scope changes; explain what the revised question can support.'),
29:('Perform QA before sharing','Test join counts, duplicate keys, totals, blanks, slicer reset, keyboard navigation, narrow-screen readability, refresh and access roles. Ask a peer to reproduce one KPI.','Technical correctness and usability are separate checks. Include uncertainty and source limitations in the report rather than concealing inconvenient exceptions.'),
30:('Tell a defensible analytical story','Present problem → evidence → interpretation → recommendation → limitation → next action. Show the metric definition and demonstrate one interaction live.','Separate observed facts from hypotheses, predictions and decisions. Supply reproducible files and a handover plan so the audience can verify the result.')}
index=[]
for p in sorted((R/'modules').rglob('lecture*.html'),key=lambda p:int(re.search(r'lecture(\d+)',p.name)[1])):
 n=int(re.search(r'lecture(\d+)',p.name)[1]);s=p.read_text()
 s=re.sub(r'<script>\s*window\.COURSE_SEARCH_INDEX\s*=.*?</script>','',s,flags=re.S)
 # Idempotence during content/layout iteration.
 s=re.sub(r'<!-- course-enhancement:start -->.*?<!-- course-enhancement:end -->','',s,flags=re.S)
 title=html.unescape(re.sub('<[^>]+>','',re.search(r'<h1[^>]*>(.*?)</h1>',s,re.S)[1]))
 task,action,interpret=practice[n]
 pieces=['<!-- course-enhancement:start -->',f'<section class="card teaching-practice" id="worked-practice"><h2>Worked practice: {html.escape(task)}</h2>',f'<p>{html.escape(action)}</p><p><strong>Interpretation check:</strong> {html.escape(interpret)}</p>']
 for lab in labs.get(n,[]):pieces.append(f'<p><a href="../../labs/{lab}.ipynb" download>Download runnable/guided lab: {html.escape(lab.replace("_"," "))}</a></p>')
 pieces.append('<p><a href="../../resources/index.html">Setup, all labs, datasets, DAX measures and capstone guidance</a> · <a href="../../resources/retail-report.html">Interactive retail teaching report</a></p></section>')
 for v in visuals:
  if n not in v['lectures']:continue
  e=lambda k:html.escape(v[k],quote=True)
  labels=[html.escape(''.join(el.itertext())) for el in ET.parse(R/'assets/visuals'/v['file']).iter('{http://www.w3.org/2000/svg}text')]
  transcript='<details class="visual-transcript"><summary>Read diagram labels (mobile text)</summary><ul>'+''.join('<li>'+label+'</li>' for label in labels)+'</ul></details>'
  pieces.append(f'<figure class="teaching-figure"><h2>{e("title")}</h2><a href="../../assets/visuals/{v["file"]}" aria-label="Open full-size editable diagram: {e("title")}"><img src="../../assets/visuals/{v["file"]}" alt="{e("alt")}" loading="lazy"></a><figcaption>{e("caption")} <a href="../../assets/visuals/{v["file"]}" download>Download editable SVG</a></figcaption><details><summary>Interpret: {e("question")}</summary><p>{e("answer")}</p></details>{transcript}</figure>')
 pieces.append(f'<section class="card completion-control"><h2>Your reading progress</h2><p>Completion is self-reported reading progress, not a mastery score. Use the lab and interpretation checks to assess understanding.</p><label><input type="checkbox" id="lectureComplete" data-complete-lecture="{n}"> I have reviewed this lecture and its practice.</label></section><!-- course-enhancement:end -->')
 s=s.replace('<div class="lecture-nav">','\n'.join(pieces)+'\n<div class="lecture-nav">')
 s=s.replace('<script src="../../assets/js/main.js">','<script src="../../assets/js/search-index.js"></script>\n  <script src="../../assets/js/main.js">') if 'search-index.js' not in s else s
 s=s.replace('DimGeography','DimRegion').replace('Fact[Amount]','Sales[NetRevenue]').replace('COUNTROWS ( Fact )','DISTINCTCOUNT ( Sales[OrderID] )')
 s=re.sub(r'Fully aligned with CS-399[^<]*\.', 'Includes practical examples and guided exercises.',s)
 s=re.sub(r'fully aligned with the CS-399[^<]*\.', 'with worked examples and test assumptions.',s)
 s=s.replace('Structured only','Primarily tabular').replace('Best of both','Lake + table layer').replace('Snowflake (with stages)','table formats such as Delta Lake or Apache Iceberg')
 if n==7:s=s.replace('invariant to monotonic transforms','generally insensitive to positive affine scaling; nonlinear transforms can alter fitted split thresholds')
 # Make executable paths consistent with notebook setup (repository root).
 s=s.replace('pd.read_csv("../../datasets/','pd.read_csv("datasets/').replace("pd.read_csv('../../datasets/","pd.read_csv('datasets/")
 p.write_text('\n'.join(line.rstrip() for line in s.splitlines())+'\n')
 index.append(dict(title=title,url=str(p.relative_to(R)),module=f'Lecture {n}',keywords=task+' '+action,summary=interpret))
(R/'assets/js/search-index.js').write_text('window.COURSE_SEARCH_INDEX = '+json.dumps(index,ensure_ascii=False,indent=2)+';\n')
p=R/'index.html';s=p.read_text();s=re.sub(r'<script>\s*window\.COURSE_SEARCH_INDEX\s*=.*?</script>','',s,flags=re.S)
if 'search-index.js' not in s:s=s.replace('<script src="assets/js/main.js">','<script src="assets/js/search-index.js"></script>\n  <script src="assets/js/main.js">')
s=s.replace('This course follows a rigorous university-level syllabus (CS 399) while delivering an interactive, industry-grade learning experience. Every concept includes theory, visual explanations, Python & Power BI implementations, labs, quizzes, and interview preparation.','This undergraduate teaching course covers the analytics lifecycle through 30 lectures, worked examples, editable visuals, Python notebooks, guided Power BI labs, quizzes and an interactive retail report. See the course guide for prerequisites, learning outcomes and suggested assessment.')
s=s.replace('Quizzes, flashcards, drag-and-drop, live code examples, and instant feedback on every lecture.','Quizzes, keyboard-accessible flashcards, downloadable notebooks, interpretation questions and an interactive retail report.')
if 'resources/index.html' not in s:s=s.replace('<div class="hero-stats">','<p><a class="nav-btn primary" href="resources/index.html">Start here: setup, labs and course resources</a> <a class="nav-btn" href="resources/retail-report.html">Explore the retail report</a></p>\n<div class="hero-stats">')
p.write_text('\n'.join(line.rstrip() for line in s.splitlines())+'\n')
